Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -21,7 +21,12 @@ jobs:
           name: users-microservice
           path: artifacts/
           run-id: ${{ github.event.workflow_run.id }} #dynamically gets the run id.
-
+      
+      # use || true to prevent job failure if empty    
+      - name: List Artifact Contents
+        run: ls -l artifacts/ || true 
+        
+          
       - name: Log in to AWS ECR
         run: |
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
