Update docker-build.yml

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -15,6 +15,10 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
+      # use || true to prevent job failure if empty    
+      - name: List Artifact Contents
+        run: ls -l artifacts/ || true 
+        
       - name: Download Build Artifact
         uses: actions/download-artifact@v4
         with:
@@ -22,9 +26,7 @@ jobs:
           path: artifacts/
           run-id: ${{ github.event.workflow_run.id }} #dynamically gets the run id.
       
-      # use || true to prevent job failure if empty    
-      - name: List Artifact Contents
-        run: ls -l artifacts/ || true 
+      
         
           
       - name: Log in to AWS ECR
